// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Result struct {
	TypeURL   string `json:"typeUrl"`
	Value     string `json:"value"`
	ValueType string `json:"valueType"`
}
